<a href="https://colab.research.google.com/github/Riddhigupta3011/Riddhigupta3011/blob/main/ANN_churn_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1 - Data Preprocessing

Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Importing Dataset

In [ ]:
dataset=pd.read_csv("/content/drive/MyDrive/Churn_Modelling.csv")

In [ ]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

Encoding categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
labelencoder=LabelEncoder()
dataset['Gender']=labelencoder.fit_transform(dataset['Gender'])
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary  Exited
0          1    15634602  Hargrave  ...               1       101348.88       1
1          2    15647311      Hill  ...               1       112542.58       0
2          3    15619304      Onio  ...               0       113931.57       1
3          4    15701354      Boni  ...               0        93826.63       0
4          5    15737888  Mitchell  ...               1        79084.10       0

[5 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
labelencoder=LabelEncoder()
dataset['Geography'] = labelencoder.fit_transform(dataset['Geography'])
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave  ...               1        101348.88       1
1          2    15647311      Hill  ...               1        112542.58       0
2          3    15619304      Onio  ...               0        113931.57       1
3          4    15701354      Boni  ...               0         93826.63       0
4          5    15737888  Mitchell  ...               1         79084.10       0

[5 rows x 14 columns]

In [ ]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

Splitting the dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

importing the keras librabries nd packages

In [ ]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

# Part 2 - Now let's make the ANN!

Initialising the ANN

In [ ]:
ANN = Sequential()
ANN=tf.keras.models.Sequential()
#Adding the input layer and the first hidden layer
ANN.add(tf.keras.layers.Dense(units=6,activation='relu'))
#Adding the second hidden layer
ANN.add(tf.keras.layers.Dense(units=6,activation='relu'))

ANN.add(tf.keras.layers.Dense(units=6,activation='softmax'))
#Adding the output layer
ANN.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
#Compiling the ANN
ANN.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [ ]:
#Fitting the ANN to the training set
ANN.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7035 - accuracy: 0.4810
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5489 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4976 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4700 - accuracy: 0.7970
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4483 - accuracy: 0.8129
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4320 - accuracy: 0.8301
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4190 - accuracy: 0.8382
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4072 - accuracy: 0.8428
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3968 - accuracy: 0.8482
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3897 - accuracy: 0.8475
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3831 - accuracy: 0.8464
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3781 - accuracy: 0.8486
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8525
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3705 - accuracy: 0.8518
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3682 - accuracy: 0.8550
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3652 - accuracy: 0.8569
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3634 - accuracy: 0.8562
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3621 - accuracy: 0.8566
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3603 - accuracy: 0.8569
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3593 - accuracy: 0.8569
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3579 - accuracy: 0.8579
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8583
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3559 - accuracy: 0.8581
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8587
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8581
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3535 - accuracy: 0.8574
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3528 - accuracy: 0.8589
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3524 - accuracy: 0.8589
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3514 - accuracy: 0.8577
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3514 - accuracy: 0.8581
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8590
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3504 - accuracy: 0.8583
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8577
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8577
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3491 - accuracy: 0.8585
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3489 - accuracy: 0.8579
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.8586
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8580
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3476 - accuracy: 0.8595
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.8577
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3473 - accuracy: 0.8581
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3468 - accuracy: 0.8591
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8587
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3466 - accuracy: 0.8591
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8584
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3467 - accuracy: 0.8572
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3462 - accuracy: 0.8594
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3462 - accuracy: 0.8584
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3455 - accuracy: 0.8593
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3460 - accuracy: 0.8590
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3455 - accuracy: 0.8579
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3452 - accuracy: 0.8575
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3451 - accuracy: 0.8585
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3451 - accuracy: 0.8580
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3449 - accuracy: 0.8575
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3452 - accuracy: 0.8585
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3446 - accuracy: 0.8594
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8580
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8581
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8576
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8595
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8589
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8589
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3441 - accuracy: 0.8600
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8586
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3441 - accuracy: 0.8601
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8587
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8577
Epoch 69/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3438 - accuracy: 0.8570
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3437 - accuracy: 0.8590
Epoch 71/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3436 - accuracy: 0.8585
Epoch 72/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3437 - accuracy: 0.8589
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3435 - accuracy: 0.8577
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3433 - accuracy: 0.8601
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3434 - accuracy: 0.8586
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3430 - accuracy: 0.8584
Epoch 77/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3434 - accuracy: 0.8602
Epoch 78/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3433 - accuracy: 0.8593
Epoch 79/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8616
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3432 - accuracy: 0.8589
Epoch 81/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3427 - accuracy: 0.8596
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3430 - accuracy: 0.8590
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8595
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3425 - accuracy: 0.8589
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3424 - accuracy: 0.8589
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8601
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3428 - accuracy: 0.8577
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.8599
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3427 - accuracy: 0.8605
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8591
Epoch 91/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3424 - accuracy: 0.8594
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8593
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3427 - accuracy: 0.8602
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3428 - accuracy: 0.8589
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3420 - accuracy: 0.8614
Epoch 96/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8612
Epoch 97/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8606
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8597
Epoch 99/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3424 - accuracy: 0.8602
Epoch 100/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3414 - accuracy: 0.8606

 # Part 3 - Making the predictions and evaluating the model

In [ ]:
#Predicting the Test set results
y_pred = ANN.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[1525,   70],
       [ 207,  198]])